# Generated by Django 3.0.7 on 2020-06-21 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant_app', '0004_auto_20200621_1914'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurantlocation',
            name='Category',
            field=models.CharField(max_length=120, null=True),
        ),
    ]
