# Generated by Django 3.0.7 on 2020-06-23 13:46

from django.db import migrations, models
import restaurant_app.validators


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant_app', '0007_auto_20200622_2230'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurantlocation',
            name='Category',
            field=models.CharField(max_length=120, null=True, validators=[restaurant_app.validators.validate_category]),
        ),
    ]
